// This may look like garbage but is actually -*- C -*-
#pragma CMOD separator ◼
#pragma CMOD module C◼align

#pragma CMOD declaration

#define as _Alignas
#define of _Alignof
#define as_is_defined 1
#define of_is_defined 1

#pragma CMOD snippet none
#pragma CMOD declaration

#define alignas			C◼align◼as
#define alignof			C◼align◼of
#define alignas_is_defined	C◼align◼as_is_defined
#define alignof_is_defined	C◼align◼of_is_defined
