// This may look like garbage but is actually -*- C -*-
#pragma CMOD separator ◼
#pragma CMOD module			C◼llong◼qsort
#pragma CMOD import 			C◼def
#pragma CMOD import llong	=	C◼llong
#pragma CMOD import compar	=	C◼llong◼compar
#pragma CMOD import qsort	=	C◼tmpl◼qsort

/*           fill snippet		local           */
#pragma CMOD fill qsort◼T	=	llong
#pragma CMOD fill qsort◼func	=	llong◼qsort
#pragma CMOD fill qsort◼compar	=	compar
