// This may look like garbage but is actually -*- C -*-
#pragma CMOD separator ◼
#pragma CMOD module C◼real◼ldouble◼bsearch
#pragma CMOD import ldouble	=	C◼real◼ldouble

#pragma CMOD import bsearch	=	C◼tmpl◼bsearch
#pragma CMOD import compar	=	C◼real◼ldouble◼compar

/*           fill snippet		local           */
#pragma CMOD fill bsearch◼T	=	ldouble
#pragma CMOD fill bsearch◼compar=	C◼real◼ldouble◼compar
