// This may look like garbage but is actually -*- C -*-
#pragma CMOD separator ◼
#pragma CMOD module			C◼real◼float◼qsort
#pragma CMOD import compar	=	C◼real◼float◼compar
#pragma CMOD import qsort	=	C◼tmpl◼qsort

/*           fill snippet		local           */
#pragma CMOD fill qsort◼T	=	C◼real◼float
#pragma CMOD fill qsort◼func	=	C◼real◼float◼qsort
#pragma CMOD fill qsort◼compar	=	C◼real◼float◼compar
