// This may look like garbage but is actually -*- C -*-
#pragma CMOD separator ◼
#pragma CMOD module			C◼real◼ldouble◼qsort
#pragma CMOD import ldouble	=	C◼real◼ldouble
#pragma CMOD import compar	=	C◼real◼ldouble◼compar
#pragma CMOD import qsort	=	C◼tmpl◼qsort

/*           fill snippet		local           */
#pragma CMOD fill qsort◼T	=	ldouble
#pragma CMOD fill qsort◼func	=	C◼real◼ldouble◼qsort
#pragma CMOD fill qsort◼compar	=	C◼real◼ldouble◼compar
