// This may look like garbage but is actually -*- C -*-
#pragma CMOD separator ◼
#pragma CMOD module			C◼schar◼qsort
#pragma CMOD import schar	=	C◼schar
#pragma CMOD import compar	=	C◼schar◼compar
#pragma CMOD import qsort	=	C◼tmpl◼qsort

/*           fill snippet		local           */
#pragma CMOD fill qsort◼T	=	schar
#pragma CMOD fill qsort◼func	=	C◼schar◼qsort
#pragma CMOD fill qsort◼compar	=	C◼schar◼compar
