// This may look like garbage but is actually -*- C -*-
#pragma CMOD separator ◼
#pragma CMOD module			  C◼size◼list
#pragma CMOD import integer		= C◼integer

#pragma CMOD import tlist		= C◼tmpl◼list
#pragma CMOD fill tlist◼T		= C◼size
#pragma CMOD fill tlist◼instance	= C◼size◼list

#pragma CMOD import ilist		= C◼interface◼list
#pragma CMOD fill ilist◼T		= C◼size
#pragma CMOD fill ilist◼instance	= C◼size◼list
