// This may look like garbage but is actually -*- C -*-
#pragma CMOD separator ◼
#pragma CMOD module			C◼uchar◼qsort
#pragma CMOD import uchar	=	C◼uchar
#pragma CMOD import compar	=	C◼uchar◼compar
#pragma CMOD import qsort	=	C◼tmpl◼qsort

/*           fill snippet		local           */
#pragma CMOD fill qsort◼T	=	uchar
#pragma CMOD fill qsort◼func	=	C◼uchar◼qsort
#pragma CMOD fill qsort◼compar	=	C◼uchar◼compar
