// This may look like garbage but is actually -*- C -*-
#pragma CMOD separator ◼
#pragma CMOD module			C◼ulong◼qsort
#pragma CMOD import ulong	=	C◼ulong
#pragma CMOD import compar	=	C◼ulong◼compar
#pragma CMOD import qsort	=	C◼tmpl◼qsort

/*           fill snippet		local           */
#pragma CMOD fill qsort◼T	=	ulong
#pragma CMOD fill qsort◼func	=	C◼ulong◼qsort
#pragma CMOD fill qsort◼compar	=	C◼ulong◼compar
