// This may look like garbage but is actually -*- C -*-
#pragma CMOD separator ◼
#pragma CMOD module			C◼ullong◼qsort
#pragma CMOD import ullong	=	C◼ullong
#pragma CMOD import compar	=	C◼ullong◼compar
#pragma CMOD import qsort	=	C◼tmpl◼qsort

/*           fill snippet		local           */
#pragma CMOD fill qsort◼T	=	ullong
#pragma CMOD fill qsort◼func	=	C◼ullong◼qsort
#pragma CMOD fill qsort◼compar	=	C◼ullong◼compar
