// This may look like garbage but is actually -*- C -*-
#pragma CMOD separator ◼
#pragma CMOD module			C◼ushort◼qsort
#pragma CMOD import ushort	=	C◼ushort
#pragma CMOD import compar	=	C◼ushort◼compar
#pragma CMOD import qsort	=	C◼tmpl◼qsort

/*           fill snippet		local           */
#pragma CMOD fill qsort◼T	=	ushort
#pragma CMOD fill qsort◼func	=	C◼ushort◼qsort
#pragma CMOD fill qsort◼compar	=	C◼ushort◼compar
