
SOURCES =					\
	C.X					\
	C\#align.X				\
	C\#assert.X				\
	C\#atomic.X				\
	C\#atomic\#flag.X			\
	C\#atomic\#rwlock.X			\
	C\#bool.X				\
	C\#cenv.X				\
	C\#char.X				\
	C\#char\#bsearch.X			\
	C\#char\#compar.X			\
	C\#char\#qsort.X			\
	C\#complex.X				\
	C\#complex\#double.X			\
	C\#complex\#float.X			\
	C\#complex\#ldouble.X			\
	C\#def.X				\
	C\#errno.X				\
	C\#fenv.X				\
	C\#fenv\#round.X			\
	C\#fenv\#except.X			\
	C\#generic.X				\
	C\#int.X				\
	C\#int\#bsearch.X			\
	C\#int\#compar.X			\
	C\#int\#qsort.X				\
	C\#integer.X				\
	C\#interface.X				\
	C\#interface\#compar.X			\
	C\#interface\#init.X			\
	C\#interface\#list.X			\
	C\#intmax.X				\
	C\#intptr.X				\
	C\#io.X					\
	C\#is.X					\
	C\#iso646.X				\
	C\#lib.X				\
	C\#llong.X				\
	C\#llong\#bsearch.X			\
	C\#llong\#compar.X			\
	C\#llong\#qsort.X			\
	C\#locale.X				\
	C\#long.X				\
	C\#long\#bsearch.X			\
	C\#long\#compar.X			\
	C\#long\#qsort.X			\
	C\#math.X				\
	C\#mem.X				\
	C\#mod.X				\
	C\#noreturn.X				\
	C\#ptrdiff.X				\
	C\#real.X				\
	C\#real\#classify.X			\
	C\#real\#double.X			\
	C\#real\#double\#bsearch.X		\
	C\#real\#double\#compar.X		\
	C\#real\#double\#qsort.X		\
	C\#real\#float.X			\
	C\#real\#float\#bsearch.X		\
	C\#real\#float\#compar.X		\
	C\#real\#float\#qsort.X			\
	C\#real\#is.X				\
	C\#real\#ldouble.X			\
	C\#real\#ldouble\#bsearch.X		\
	C\#real\#ldouble\#compar.X		\
	C\#real\#ldouble\#qsort.X		\
	C\#schar.X				\
	C\#schar\#bsearch.X			\
	C\#schar\#compar.X			\
	C\#schar\#qsort.X			\
	C\#short.X				\
	C\#short\#bsearch.X			\
	C\#short\#compar.X			\
	C\#short\#qsort.X			\
	C\#sig.X				\
	C\#sig\#atomic.X			\
	C\#size.X				\
	C\#size\#bsearch.X			\
	C\#size\#compar.X			\
	C\#size\#list.X				\
	C\#size\#qsort.X			\
	C\#sizeptr.X				\
	C\#sizeptr\#list.X			\
	C\#snippet.X				\
	C\#snippet\#INITIALIZER.X		\
	C\#snippet\#alloc.X			\
	C\#snippet\#init.X			\
	C\#snippet\#minmax.X			\
	C\#std.X				\
	C\#std\#align.X				\
	C\#std\#arg.X				\
	C\#std\#assert.X			\
	C\#std\#atomic.X			\
	C\#std\#bool.X				\
	C\#std\#complex.X			\
	C\#std\#ctype.X				\
	C\#std\#def.X				\
	C\#std\#errno.X				\
	C\#std\#fenv.X				\
	C\#std\#float.X				\
	C\#std\#int.X				\
	C\#std\#inttypes.X			\
	C\#std\#io.X				\
	C\#std\#iso646.X			\
	C\#std\#lib.X				\
	C\#std\#limits.X			\
	C\#std\#locale.X			\
	C\#std\#math.X				\
	C\#std\#noreturn.X			\
	C\#std\#setjmp.X			\
	C\#std\#signal.X			\
	C\#std\#string.X			\
	C\#std\#tgmath.X			\
	C\#std\#threads.X			\
	C\#std\#time.X				\
	C\#std\#uchar.X				\
	C\#std\#wchar.X				\
	C\#std\#wctype.X			\
	C\#str.X				\
	C\#str\#bsearch.X			\
	C\#str\#compar.X			\
	C\#str\#qsort.X				\
	C\#thrd.X				\
	C\#thrd\#cnd.X				\
	C\#thrd\#mtx.X				\
	C\#thrd\#once.X				\
	C\#thrd\#tss.X				\
	C\#time.X				\
	C\#time\#cal.X				\
	C\#time\#spec.X				\
	C\#tmpl.X				\
	C\#tmpl\#bsearch.X			\
	C\#tmpl\#compar.X			\
	C\#tmpl\#list.X				\
	C\#tmpl\#qsort.X			\
	C\#uchar.X				\
	C\#uchar\#bsearch.X			\
	C\#uchar\#compar.X			\
	C\#uchar\#qsort.X			\
	C\#uintmax.X				\
	C\#uintptr.X				\
	C\#ullong.X				\
	C\#ullong\#bsearch.X			\
	C\#ullong\#compar.X			\
	C\#ullong\#qsort.X			\
	C\#ulong.X				\
	C\#ulong\#bsearch.X			\
	C\#ulong\#compar.X			\
	C\#ulong\#qsort.X			\
	C\#unsigned.X				\
	C\#unsigned\#bsearch.X			\
	C\#unsigned\#compar.X			\
	C\#unsigned\#qsort.X			\
	C\#ushort.X				\
	C\#ushort\#bsearch.X			\
	C\#ushort\#compar.X			\
	C\#ushort\#qsort.X			\
	C\#va.X					\
	C\#wchar.X				\
	C\#wcs.X				\
	C\#wint.X

OBJECTS = ${SOURCES:.X=.a}
DEPS    = ${SOURCES:.X=.dep}

TARGET = libC.a

CMOD=../Cmod
MAKEHEADER=../makeheader

TOOLS = ${CMOD} ${MAKEHEADER}

CMODEP = ${CMOD} -M

CFLAGS	?= -std=c11 -Wall -g -O3 -march=native -fno-common -fdata-sections -ffunction-sections ${COPTS}
LDFLAGS ?= -Wl,--gc-sections

%.dep : %.X # Makefile
	@${CMODEP} $*.X -o $*.dep

%.a : %.dep %.X ${CMOD}
	${CMOD} -c ${CFLAGS} ${LDFLAGS} $*.X

% : %.dep %.a ${CMOD}
	${CMOD}  $*.a -o $* ${CFLAGS} ${LDFLAGS}




.SECONDEXPANSION:
target : ${TARGET} $${DEPENDCIES} # ${OBJECTS}

libC.a : ${OBJECTS}
	$(shell TMP=$$(mktemp -d) ;                   \
	 cp ${OBJECTS} $${TMP} ;                      \
	 cd $${TMP} ;                                 \
	 for f in *.a ; do ar x $$f ; rm $$f ; done ; \
	 ar rs $(shell pwd)/libC.a * ;                \
	 rm * ;                                       \
	 cd .. ;                                      \
	 rmdir $${TMP})

libC.dep : ${DEPS}
	cat ${DEPS} > libC.dep

all : depend ${OBJECTS}

clean :
	rm -f ${DEPS} ${OBJECTS} ${TARGET}

depend : ${SOURCES:.X=.dep}

-include ${SOURCES:.X=.dep} $${DEPENDCIES}
